### ISSUE TITLE
is the final results absolute angle In the head coordinate system in demo.py ?

### ISSUE THREAD

**Issue by huxian0402** [hysts/pytorch_mpiigaze#15]
Hello, is the final results (logger.info(f'[face] pitch: {pitch:.2f}, yaw: {yaw:.2f}'))  absolute angle in the head coordinate system or in the World coordinate system in your demo.py? I see that after getting the result from network,   denormalize_gaze_vector  function is used to get the final gaze.I always wonder that is function denormalize_gaze_vector convert the gaze results in  in the head coordinate system to the World coordinate system? @hysts

**Comment by hysts** [comment]
Hi, @huxian0402 

Hmm... I think my original intention was to display gaze directions in the head coordinate system, but as you pointed out, something seems wrong. Visualization may also be incorrect. I'll check the code, but it may take some time because I don't have much time recently. If you find out what's wrong with it, please let me know. Thank you.

**Comment by hysts** [comment]
@huxian0402
I think I was a little confused. After all, the displayed angles are in the camera coordinate system, not the relative angle to the head pose.
