### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by yuzehui1996** [hysts/pytorch_mpiigaze#16]
Can you share the pretrained models for the resnet_simple_14 on the mpiifacegaze dataset?
Thanks a lot!

**Comment by hysts** [comment]
Hi, @yuzehui1996 

You can download it [here](https://github.com/hysts/pytorch_mpiigaze_demo/releases).
FYI, if you want to try out the demo program, it's easier to use [this repo](https://github.com/hysts/pytorch_mpiigaze_demo) because it's pip-installable and will automatically download the pretrained models.

**Comment by yuzehui1996** [comment]
Thanks a lot!
