### ISSUE TITLE
excuse me，i have a question

### ISSUE THREAD

**Issue by LiuZiMing000** [hysts/pytorch_mpiigaze#31]
Hello, my English is not very good, please forgive me. Did your code run successfully? I ran under the win10 system, and the data set was ready and preprocessed, but I still got some error when I ran the train. I don’t know why, it’s very strange.

**Comment by hysts** [comment]
@LiuZiMing000 

Ah, that error is caused by [this code](https://github.com/hysts/pytorch_mpiigaze/blob/a8cb2e344068bf75c7fdbbd732db88fa09ddb618/gaze_estimation/utils.py#L56-L59), which prevents to accidentally overwrite an existing experiment directory.
If you delete the experiment directory and run it again, it should work.
