### ISSUE TITLE
How to set normalized camera projection matrix

### ISSUE THREAD

**Issue by yuyaya-foifoi** [hysts/pytorch_mpiigaze#34]
Hi, @hysts thank you again for sharing your work

Can you tell me how you set [normalized camera projection matrix](https://github.com/hysts/pytorch_mpiigaze/blob/a51b5c824b7d186846770453a7e731cd69e8a952/data/calib/normalized_camera_params_face.yaml#L6)?

**Comment by hysts** [comment]
@yuyaya-foifoi 

I thought it was written in the paper, but it seems not. I can't remember where it came from. Hmm...
Maybe from some code?

**Comment by yuyaya-foifoi** [comment]
@hysts 

Thank you for your reply.
I see, do you remember which code you referred to ?

**Comment by hysts** [comment]
@yuyaya-foifoi 

I don't remember, but anyway the code on the project page seems to use different parameters, so I think the parameters in this repo are incorrect.

**Comment by yuyaya-foifoi** [comment]
@hysts 

It's a parameter in the HeadPoseEstimator in headposeestimator.cpp, right?

I changed current parameter to the parameter in  HeadPoseEstimator and ran demo.py, but qualitatively, the accuracy decreased. (the gaze vector in the image didnt not move.)
I also changed parame cx and cy to the size of my camera image, but it was still qualitatively inaccurate.

For now, it seems better not to change the [current implementation](https://github.com/hysts/pytorch_mpiigaze/blob/43601e851bc82cee4323ce6b5abf0ab4ff2c0b60/data/calib/normalized_camera_params_face.yaml#L6).

**Comment by hysts** [comment]
@yuyaya-foifoi 

Oh, thanks for the info. As you said, the parameters they are using doesn't seem to be working. I didn't noticed it due to a bug in the demo program I used when I wrote the comment above. Sorry about that.

And thanks to you, I remember that the parameters in the project page didn't work when I was developing this repo, and that I googled for a code with parameters that works. And I think [this](https://git.hcics.simtech.uni-stuttgart.de/public-projects/opengaze/-/blob/master/src/gaze_estimator.cpp#L89) is where the parameter in this repo came from.

**Comment by yuyaya-foifoi** [comment]
@hysts 

Thank you for sharing.
I see, I understand that the effectiveness of [this parameter](https://git.hcics.simtech.uni-stuttgart.de/public-projects/opengaze/-/blob/master/src/gaze_estimator.cpp#L89) seems to be empirically proven. 
If you find out what this parameter theoretically means, please share it. I'll share it if I find out something.
